# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('isAction', models.BooleanField(default=False)),
                ('result', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
