# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=50)),
                ('caseId', models.IntegerField(default=0)),
                ('modelName', models.CharField(max_length=50)),
                ('caseDetail', models.CharField(max_length=100)),
                ('isAction', models.BooleanField(default=False)),
                ('result', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=20, null=True)),
                ('action_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='testcase',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together=set([('id', 'caseId')]),
        ),
    ]
