# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testenvData', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='envdata',
            unique_together=set([('id', 'phone')]),
        ),
    ]
