# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testenvData', '0002_auto_20180110_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='serverdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=50, null=True)),
                ('ip', models.CharField(max_length=50, null=True)),
                ('port', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('isAvailable', models.CharField(max_length=4, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='envdata',
            name='channle',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='envdata',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='envdata',
            name='role',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
